import idaapi

class XLiveImportFix:

    xlive_dict = {
        'xlive_1': 'XLive__TitleExports_XWSAStartup@8',
        'xlive_2': 'XLive__TitleExports_XWSACleanup@0',
        'xlive_3': 'XLive__TitleExports_XSocketCreate@12',
        'xlive_4': 'XLive__TitleExports_XSocketClose@4',
        'xlive_5': 'XLive__TitleExports_XSocketShutdown@8',
        'xlive_6': 'XLive__TitleExports_XSocketIOCTLSocket@12',
        'xlive_7': 'XLive__TitleExports_XSocketSetSockOpt@20',
        'xlive_8': 'XLive__TitleExports_XSocketGetSockOpt@20',
        'xlive_9': 'XLive__TitleExports_XSocketGetSockName@12',
        'xlive_10': 'XLive__TitleExports_XSocketGetPeerName@12',
        'xlive_11': 'XLive__TitleExports_XSocketBind@12',
        'xlive_12': 'XLive__TitleExports_XSocketConnect@12',
        'xlive_13': 'XLive__TitleExports_XSocketListen@8',
        'xlive_14': 'XLive__TitleExports_XSocketAccept@12',
        'xlive_15': 'XLive__TitleExports_XSocketSelect@20',
        'xlive_16': 'XLive__TitleExports_XWSAGetOverlappedResult@20',
        'xlive_17': 'XLive__TitleExports_XWSACancelOverlappedIO@4',
        'xlive_18': 'XLive__TitleExports_XSocketRecv@16',
        'xlive_19': 'XLive__TitleExports_XWSARecv@28',
        'xlive_20': 'XLive__TitleExports_XSocketRecvFrom@24',
        'xlive_21': 'XLive__TitleExports_XWSARecvFrom@36',
        'xlive_22': 'XLive__TitleExports_XSocketSend@16',
        'xlive_23': 'XLive__TitleExports_XWSASend@28',
        'xlive_24': 'XLive__TitleExports_XSocketSendTo@24',
        'xlive_25': 'XLive__TitleExports_XWSASendTo@36',
        'xlive_26': 'XLive__TitleExports_XSocketInet_Addr@4',
        'xlive_27': 'XLive__TitleExports_XWSAGetLastError@0',
        'xlive_28': 'XLive__TitleExports_XWSASetLastError@4',
        'xlive_29': 'XLive__TitleExports_XWSACreateEvent@0',
        'xlive_30': 'XLive__TitleExports_XWSACloseEvent@4',
        'xlive_31': 'XLive__TitleExports_XWSASetEvent@4',
        'xlive_32': 'XLive__TitleExports_XWSAResetEvent@4',
        'xlive_33': 'XLive__TitleExports_XWSAWaitForMultipleEvents@20',
        'xlive_34': 'XLive__TitleExports___XWSAFDIsSet@8',
        'xlive_35': 'XLive__TitleExports_XWSAEventSelect@12',
        'xlive_37': 'XLive__TitleExports_XSocketHTONL@4',
        'xlive_38': 'XLive__TitleExports_XSocketNTOHS@4',
        'xlive_39': 'XLive__TitleExports_XSocketHTONL@4_2',
        'xlive_40': 'XLive__TitleExports_XSocketNTOHS@4_2',
        'xlive_51': 'XLive__TitleExports_XNetStartup@4',
        'xlive_52': 'XLive__TitleExports_XNetCleanup@0',
        'xlive_53': 'XLive__TitleExports_XNetRandom@8',
        'xlive_54': 'XLive__TitleExports_XNetCreateKey@8',
        'xlive_55': 'XLive__TitleExports_XNetRegisterKey@8',
        'xlive_56': 'XLive__TitleExports_XNetUnregisterKey@4',
        'xlive_57': 'XLive__TitleExports_XNetXnAddrToInAddr@12',
        'xlive_58': 'XLive__TitleExports_XNetServerToInAddr@12',
        'xlive_60': 'XLive__TitleExports_XNetInAddrToXnAddr@12',
        'xlive_62': 'XLive__TitleExports_XNetInAddrToString@12',
        'xlive_63': 'XLive__TitleExports_XNetUnregisterInAddr@4',
        'xlive_64': 'XLive__TitleExports_XNetXnAddrToMachineId@8',
        'xlive_65': 'XLive__TitleExports_XNetConnect@4',
        'xlive_66': 'XLive__TitleExports_XNetGetConnectStatus@4',
        'xlive_67': 'XLive__TitleExports_XNetDnsLookup@12',
        'xlive_68': 'XLive__TitleExports_XNetDnsRelease@4',
        'xlive_69': 'XLive__TitleExports_XNetQosListen@20',
        'xlive_70': 'XLive__TitleExports_XNetQosLookup@48',
        'xlive_71': 'XLive__TitleExports_XNetQosServiceLookup@12',
        'xlive_72': 'XLive__TitleExports_XNetQosRelease@4',
        'xlive_73': 'XLive__TitleExports_XNetGetTitleXnAddr@4',
        'xlive_75': 'XLive__TitleExports_XNetGetEthernetLinkStatus@0',
        'xlive_76': 'XLive__TitleExports_XNetGetBroadcastVersionStatus@4',
        'xlive_77': 'XLive__TitleExports_XNetQosGetListenStats@8',
        'xlive_78': 'XLive__TitleExports_XNetGetOpt@12',
        'xlive_79': 'XLive__TitleExports_XNetSetOpt@12',
        'xlive_81': 'XLive__TitleExports_XNetReplaceKey@8',
        'xlive_82': 'XLive__TitleExports_XNetGetXnAddrPlatform@8',
        'xlive_83': 'XLive__TitleExports_XNetGetSystemLinkPort@4',
        'xlive_84': 'XLive__TitleExports_XNetSetSystemLinkPort@4',
        'xlive_472': 'XLive__XCustomSetAction@12',
        'xlive_473': 'XLive__XCustomGetLastActionPress@12',
        'xlive_474': 'XLive__XCustomSetDynamicActions@20',
        'xlive_476': 'XLive__XCustomGetLastActionPressEx@20',
        'xlive_477': 'XLive__XCustomRegisterDynamicActions@0',
        'xlive_478': 'XLive__XCustomUnregisterDynamicActions@0',
        'xlive_479': 'XLive__XCustomGetCurrentGamercard@8',
        'xlive_651': 'XLive__XNotifyGetNext@16',
        'xlive_652': 'XLive__XNotifyPositionUI@4',
        'xlive_653': 'XLive__XNotifyDelayUI@4',
        'xlive_1082': 'XLive__XGetOverlappedExtendedError@4',
        'xlive_1083': 'XLive__XGetOverlappedResult@12',
        'xlive_5000': 'XLive_?XLiveInitialize@@YGJPAU_XLIVE_INITIALIZE_INFO@@@Z',
        'xlive_5001': 'XLive__XLiveInput@4',
        'xlive_5002': 'XLive__XLiveRender@0',
        'xlive_5003': 'XLive__XLiveUnInitialize@0',
        'xlive_5005': 'XLive__XLiveOnCreateDevice@8',
        'xlive_5006': 'XLive__XLiveOnDestroyDevice@0',
        'xlive_5007': 'XLive__XLiveOnResetDevice@4',
        'xlive_5008': 'XLive__XHVCreateEngine@12',
        'xlive_5010': 'XLive__XLiveRegisterDataSection@12',
        'xlive_5011': 'XLive__XLiveUnregisterDataSection@4',
        'xlive_5012': 'XLive__XLiveUpdateHashes@8',
        'xlive_5016': 'XLive__XLivePBufferAllocate@8',
        'xlive_5017': 'XLive__XLivePBufferFree@4',
        'xlive_5018': 'XLive__XLivePBufferGetByte@12',
        'xlive_5019': 'XLive__XLivePBufferSetByte@12',
        'xlive_5020': 'XLive__XLivePBufferGetDWORD@12',
        'xlive_5021': 'XLive__XLivePBufferSetDWORD@12',
        'xlive_5022': 'XLive__XLiveGetUpdateInformation@4',
        'xlive_5023': 'XLive__XNetGetCurrentAdapter@8',
        'xlive_5024': 'XLive__XLiveUpdateSystem@4',
        'xlive_5025': 'XLive__XLiveGetLiveIdError@16',
        'xlive_5026': 'XLive__XLiveSetSponsorToken@8',
        'xlive_5027': 'XLive__XLiveUninstallTitle@4',
        'xlive_5028': 'XLive__XLiveLoadLibraryEx@12',
        'xlive_5029': 'XLive__XLiveFreeLibrary@4',
        'xlive_5030': 'XLive__XLivePreTranslateMessage@4',
        'xlive_5031': 'XLive__XLiveSetDebugLevel@8',
        'xlive_5032': 'XLive__XLiveVerifyArcadeLicense@8',
        'xlive_5034': 'XLive__XLiveProtectData@20',
        'xlive_5035': 'XLive__XLiveUnprotectData@20',
        'xlive_5036': 'XLive__XLiveCreateProtectedDataContext@8',
        'xlive_5037': 'XLive__XLiveQueryProtectedDataInformation@8',
        'xlive_5038': 'XLive__XLiveCloseProtectedDataContext@4',
        'xlive_5039': 'XLive__XLiveVerifyDataFile@4',
        'xlive_5206': 'XLive__XShowMessagesUI@4',
        'xlive_5208': 'XLive__XShowGameInviteUI@16',
        'xlive_5209': 'XLive__XShowMessageComposeUI@16',
        'xlive_5210': 'XLive__XShowFriendRequestUI@12',
        'xlive_5212': 'XLive__XShowCustomPlayerListUI@48',
        'xlive_5214': 'XLive__XShowPlayerReviewUI@12',
        'xlive_5215': 'XLive__XShowGuideUI@4',
        'xlive_5216': 'XLive__XShowKeyboardUI@32',
        'xlive_5218': 'XLive__XShowArcadeUI@4',
        'xlive_5230': 'XLive__XLocatorServerAdvertise@60',
        'xlive_5231': 'XLive__XLocatorServerUnAdvertise@8',
        'xlive_5233': 'XLive__XLocatorGetServiceProperty@16',
        'xlive_5234': 'XLive__XLocatorCreateServerEnumerator@40',
        'xlive_5235': 'XLive__XLocatorCreateServerEnumeratorByIDs@32',
        'xlive_5236': 'XLive__XLocatorServiceInitialize@8',
        'xlive_5237': 'XLive__XLocatorServiceUnInitialize@4',
        'xlive_5238': 'XLive__XLocatorCreateKey@8',
        'xlive_5250': 'XLive__XShowAchievementsUI@4',
        'xlive_5251': 'XLive__XCloseHandle@4',
        'xlive_5252': 'XLive__XShowGamerCardUI@12',
        'xlive_5254': 'XLive__XCancelOverlapped@4',
        'xlive_5255': 'XLive__XEnumerateBack@20',
        'xlive_5256': 'XLive__XEnumerate@20',
        'xlive_5257': 'XLive__XLiveManageCredentials@16',
        'xlive_5258': 'XLive__XLiveSignout@4',
        'xlive_5259': 'XLive__XLiveSignin@16',
        'xlive_5260': 'XLive__XShowSigninUI@8',
        'xlive_5261': 'XLive__XUserGetXUID@8',
        'xlive_5262': 'XLive__XUserGetSigninState@4',
        'xlive_5263': 'XLive__XUserGetName@12',
        'xlive_5264': 'XLive__XUserAreUsersFriends@20',
        'xlive_5265': 'XLive__XUserCheckPrivilege@12',
        'xlive_5266': 'XLive__XShowMessageBoxUI@36',
        'xlive_5267': 'XLive__XUserGetSigninInfo@12',
        'xlive_5270': 'XLive__XNotifyCreateListener@8',
        'xlive_5271': 'XLive__XShowPlayersUI@4',
        'xlive_5273': 'XLive__XUserReadGamerPictureByKey@24',
        'xlive_5274': 'XLive__XUserAwardGamerPicture@16',
        'xlive_5275': 'XLive__XShowFriendsUI@4',
        'xlive_5276': 'XLive__XUserSetProperty@16',
        'xlive_5277': 'XLive__XUserSetContext@12',
        'xlive_5278': 'XLive__XUserWriteAchievements@12',
        'xlive_5279': 'XLive__XUserReadAchievementPicture@28',
        'xlive_5280': 'XLive__XUserCreateAchievementEnumerator@36',
        'xlive_5281': 'XLive__XUserReadStats@32',
        'xlive_5282': 'XLive__XUserReadGamerPicture@24',
        'xlive_5284': 'XLive__XUserCreateStatsEnumeratorByRank@28',
        'xlive_5285': 'XLive__XUserCreateStatsEnumeratorByRating@32',
        'xlive_5286': 'XLive__XUserCreateStatsEnumeratorByXuid@32',
        'xlive_5287': 'XLive__XUserResetStatsView@12',
        'xlive_5288': 'XLive__XUserGetProperty@16',
        'xlive_5289': 'XLive__XUserGetContext@12',
        'xlive_5290': 'XLive__XUserGetReputationStars@4',
        'xlive_5291': 'XLive__XUserResetStatsViewAllUsers@8',
        'xlive_5292': 'XLive__XUserSetContextEx@16',
        'xlive_5293': 'XLive__XUserSetPropertyEx@20',
        'xlive_5294': 'XLive__XLivePBufferGetByteArray@16',
        'xlive_5295': 'XLive__XLivePBufferSetByteArray@16',
        'xlive_5296': 'XLive__XLiveGetLocalOnlinePort@4',
        'xlive_5297': 'XLive__XLiveInitializeEx@8',
        'xlive_5298': 'XLive__XLiveGetGuideKey@4',
        'xlive_5299': 'XLive__XShowGuideKeyRemapUI@4',
        'xlive_5300': 'XLive__TitleExport_XSessionCreate@32',
        'xlive_5303': 'XLive__TitleExport_XStringVerify@28',
        'xlive_5304': 'XLive__TitleExport_XStorageUploadFromMemoryGetProgress@16',
        'xlive_5305': 'XLive__TitleExport_XStorageUploadFromMemory@20',
        'xlive_5306': 'XLive__TitleExport_XStorageEnumerate@28',
        'xlive_5307': 'XLive__TitleExport_XStorageDownloadToMemoryGetProgress@16',
        'xlive_5308': 'XLive__TitleExport_XStorageDelete@12',
        'xlive_5309': 'XLive__TitleExport_XStorageBuildServerPathByXuid@32',
        'xlive_5310': 'XLive__TitleExport_XOnlineStartup@0',
        'xlive_5311': 'XLive__TitleExport_XOnlineCleanup@0',
        'xlive_5312': 'XLive__TitleExport_XFriendsCreateEnumerator@20',
        'xlive_5313': 'XLive__TitleExport_XPresenceInitialize@4',
        'xlive_5314': 'XLive__XUserMuteListQuery@16',
        'xlive_5315': 'XLive__TitleExport_XInviteGetAcceptedInfo@8',
        'xlive_5316': 'XLive__TitleExport_XInviteSend@20',
        'xlive_5317': 'XLive__TitleExport_XSessionWriteStats@24',
        'xlive_5318': 'XLive__TitleExport_XSessionStart@12',
        'xlive_5319': 'XLive__TitleExport_XSessionSearchEx@44',
        'xlive_5320': 'XLive__TitleExport_XSessionSearchByID@24',
        'xlive_5321': 'XLive__TitleExport_XSessionSearch@40',
        'xlive_5322': 'XLive__TitleExport_XSessionModify@20',
        'xlive_5323': 'XLive__TitleExport_XSessionMigrateHost@16',
        'xlive_5324': 'XLive__TitleExport_XOnlineGetNatType@0',
        'xlive_5325': 'XLive__TitleExport_XSessionLeaveLocal@16',
        'xlive_5326': 'XLive__TitleExport_XSessionJoinRemote@20',
        'xlive_5327': 'XLive__TitleExport_XSessionJoinLocal@20',
        'xlive_5328': 'XLive__TitleExport_XSessionGetDetails@16',
        'xlive_5329': 'XLive__TitleExport_XSessionFlushStats@8',
        'xlive_5330': 'XLive__TitleExport_XSessionDelete@8',
        'xlive_5331': 'XLive__TitleExport_XUserReadProfileSettings@28',
        'xlive_5332': 'XLive__TitleExport_XSessionEnd@8',
        'xlive_5333': 'XLive__TitleExport_XSessionArbitrationRegister@28',
        'xlive_5334': 'XLive__XOnlineGetServiceInfo@8',
        'xlive_5335': 'XLive__XTitleServerCreateEnumerator@16',
        'xlive_5336': 'XLive__TitleExport_XSessionLeaveRemote@16',
        'xlive_5337': 'XLive__TitleExport_XUserWriteProfileSettings@16',
        'xlive_5338': 'XLive__TitleExport_XPresenceSubscribe@12',
        'xlive_5339': 'XLive__TitleExport_XUserReadProfileSettingsByXuid@36',
        'xlive_5340': 'XLive__TitleExport_XPresenceCreateEnumerator@28',
        'xlive_5341': 'XLive__TitleExport_XPresenceUnsubscribe@12',
        'xlive_5342': 'XLive__TitleExport_XSessionModifySkill@16',
        'xlive_5343': 'XLive__TitleExport_XSessionCalculateSkill@20',
        'xlive_5344': 'XLive__TitleExport_XStorageBuildServerPath@28',
        'xlive_5345': 'XLive__TitleExport_XStorageDownloadToMemory@28',
        'xlive_5346': 'XLive__TitleExport_XUserEstimateRankForRating@20',
        'xlive_5347': 'XLive__XLiveProtectedLoadLibrary@20',
        'xlive_5348': 'XLive__XLiveProtectedCreateFile@36',
        'xlive_5349': 'XLive__XLiveProtectedVerifyFile@12',
        'xlive_5350': 'XLive__XLiveContentCreateAccessHandle@28',
        'xlive_5351': 'XLive__XLiveContentInstallPackage@12',
        'xlive_5352': 'XLive__XLiveContentUninstall@12',
        'xlive_5354': 'XLive__XLiveContentVerifyInstalledPackage@8',
        'xlive_5355': 'XLive__XLiveContentGetPath@16',
        'xlive_5356': 'XLive__XLiveContentGetDisplayName@16',
        'xlive_5357': 'XLive__XLiveContentGetThumbnail@16',
        'xlive_5358': 'XLive__XLiveContentInstallLicense@12',
        'xlive_5359': 'XLive__XLiveGetUPnPState@4',
        'xlive_5360': 'XLive__XLiveContentCreateEnumerator@16',
        'xlive_5361': 'XLive__XLiveContentRetrieveOffersByDate@24',
        'xlive_5362': 'XLive__XLiveMarketplaceDoesContentIdMatch@8',
        'xlive_5363': 'XLive__XLiveContentGetLicensePath@16',
        'xlive_5365': 'XLive__XShowMarketplaceUI@20',
        'xlive_5366': 'XLive__XShowMarketplaceDownloadItemsUI@24',
        'xlive_5367': 'XLive__TitleExport_XContentGetMarketplaceCounts@20',
        'xlive_5370': 'XLive__TitleExport_XMarketplaceConsumeAssets@16',
        'xlive_5371': 'XLive__XMarketplaceCreateAssetEnumerator@16',
        'xlive_5372': 'XLive__XMarketplaceCreateOfferEnumerator@24',
        'xlive_5374': 'XLive__XMarketplaceGetDownloadStatus@16',
        'xlive_5375': 'XLive__XMarketplaceGetImageUrl@20',
        'xlive_5376': 'XLive__XMarketplaceCreateOfferEnumeratorByOffering@24',
        'xlive_5377': 'XLive__TitleExport_XUserFindUsers@28' 
    }

    def import_iterator(self, ea, name, ord):
        self.items.append((ea, '' if not name else name, ord))

        if not name:
            print("%08x: ord#%d" % (ea, ord))
        else:
            print("%08x: %s (ord#%d)" % (ea, name, ord))

        # True -> Continue enumeration
        return True

    def FixImports(self):

        self.items = []

        nimps = idaapi.get_import_module_qty()
        for mod_index in range(0, nimps):
            name = idaapi.get_import_module_name(mod_index)
            if not name or name != "xlive":
                continue

            print("Enumerating imports...")
            idaapi.enum_import_names(mod_index, self.import_iterator)

            print("Fixing imports...")
            for ea, name, ord in self.items:
                if not name:
                    continue

                print(self.xlive_dict[name[6:]])

                #idaapi.set_name(ea, name, idaapi.SN_NOWARN)

        print("Done!")

def main():
    print("XLIVE Import Fixer")
    print("=================")
    global XLiveImportFix
    XLiveImportFix().FixImports()

main()